### ISSUE TITLE
boss battle in night caves

### ISSUE THREAD

**Issue by kvonspiczak** [godot-wildlings/gwj7#12]

**Comment by plexsoup** [comment]
We need to figure out what the boss battle should look like. What makes the big bad demon scary?

**Comment by plexsoup** [comment]
I made Baphomet.tscn and placed it in NightCaves.tscn. It uses the RangedEnemy.gd script.
It's not behaving well though. Shooting the wrong direction and stuff. It'll need some troubleshooting.

**Comment by plexsoup** [comment]
Boss seems ok now, but it needs a few tweaks.

- [ ] more behaviour
- [ ] more feedback / response to hits
- [ ] some way to know how close it is to death.

**Comment by plexsoup** [comment]
Baphomet spawns creeps now.
It wouldn't be good enough for a professional game, but it'll do for a game jam.
